### ISSUE TITLE
Wrong module output on package.json

### ISSUE THREAD

**Issue by 0b5vr** [greggman/webgl-memory#4]
### Context

I'm using the framework `vite` for the first time in the version `2.7.2` and am trying to use `webgl-memory@1.0.7` in my project.

### Problem

https://github.com/greggman/webgl-memory/blob/7edb852512b98fba5ef7b3ad8d0590a72b308bc5/package.json#L6

This does not work properly on my vite setup.
The package served from npm does not contain `/src/webgl-memory.js`, it's just `/webgl-memory.js` .

Here's the error: `[vite:resolve] Failed to resolve entry for package "webgl-memory". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "webgl-memory". The package may have incorrect main/module/exports specified in its package.json.`

I'm not sure what is the intention that you set here `/src/webgl-memory.js` but it will work by changing here to `/webgl-memory.js` by my hand.

Since it's my first time using vite, I have no idea why vite complains about it honestly, I'm sorry.

Here's how the current package look like: https://www.unpkg.com/browse/webgl-memory@1.0.7/

### Also

This package really saved my life so far.

**Comment by greggman** [comment]
Thanks for the report. Fixed.

**Comment by 0b5vr** [comment]
Worked! Thanks!
